services:
  smtp:
    image: dockage/mailcatcher:0.8.2
    ports:
      - 1080:1080
      - 1025:1025
  mongodb:
    image: mongo:4.4.18
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ignition
      - MONGO_INITDB_ROOT_PASSWORD=ignition
    networks:
      primary-network:
        aliases:
          - mongo-db
  pgres:
    image: postgres:16
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      primary-network:
        aliases:
          - pg-db
    environment:
      - POSGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pgres
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    volumes:
      - mssql-data:/var/opt/mssql
    restart: always
    networks:
      primary-network:
        aliases:
          - main-db

networks:
  primary-network:
volumes:
  mongodb-data:
  pg-data:
  mssql-data:

