services:
  main-gw:
    build:
      context: gw-build
      args:
        IGNITION_VERSION: 8.1.48
    hostname: main-host
    container_name: main-gw
    ports:
      - 9050:8088
    volumes:
      - main-gw-data:/usr/local/bin/ignition/data
     # - ./gw-init/gold_gw.gwbk:/restore.gwbk
     # - ./gw-init/gateway-uuid.txt:/usr/local/bin/ignition/data/.uuid
     # - ./gw-init/gateway-metro-keystore:/usr/local/bin/ignition/data/local/metro-keystore
    networks:
      - gw-network
    environment:
      - IGNITION_EDITION=standard
      - GATEWAY_ADMIN_PASSWORD=katlego
      - ACCEPT_IGNITION_EULA=Y
    labels:
      tsdproxy.enable: true
      tsdproxy.ephemeral: false
    restart: unless-stopped
    command: >
      -n main-gw
      -m 1024
   #   -r /restore.gwbk
networks:
  gw-network:
volumes:
  main-gw-data:

#are you picking up these changes?

#hello world
