services:
  primary:
    build:
      context: primary-build
      args:
        IGNITION_VERSION: 8.1.48
    hostname: primary
    container_name: primary
    ports:
      - 9094:8088
      - 1883:1883
    volumes:
      - primary-data:/usr/local/bin/ignition/data
     # - ./gw-init/primary.gwbk:/restore.gwbk
     # - ./gw-init/primary-uuid.txt:/usr/local/bin/ignition/data/.uuid
     # - ./gw-init/primary-metro-keystore:/usr/local/bin/ignition/data/local/metro-keystore
    #  - ./pylib/speciallibrary.py:/usr/local/bin/ignition/user-lib/pylib/speciallibrary.py
    networks:
     # - edge-network
    #  - backup-network
      - primary-network
    environment:
      - IGNITION_EDITION=standard
      - GATEWAY_ADMIN_PASSWORD=katlego
      - ACCEPT_IGNITION_EULA=Y
      - GATEWAY_MODULES_ENABLED=alarm-notification,enterprise-administration,opc-ua,perspective,reporting,sfc,sms-notification,sql-bridge,symbol-factory,tag-historian,voice-notification,web-developer
    command: >
      -n primary-gateway
      -m 2048
    #  -r /restore.gwbk
  smtp:
    image: dockage/mailcatcher:0.8.2
    container_name: stmp
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      primary-network:
        aliases:
          - stmp

  mongodb:
    image: mongo:4.4.18
    ports:
      - 27017:27017
    container_name: mongodb
    volumes:
      - mongodb-data:/data/db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ignition
      - MONGO_INITDB_ROOT_PASSWORD=ignition
    networks:
      primary-network:
        aliases:
          - mongo-db
  pgres:
    image: postgres:16
    container_name: pgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      primary-network:
        aliases:
          - pg-db
    environment:
      - POSGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pgres
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    volumes:
      - mssql-data:/var/opt/mssql
    restart: always
    networks:
      primary-network:
        aliases:
          - main-db

networks:
  primary-network:
volumes:
  mongodb-data:
  pg-data:
  mssql-data:
  primary-data:

