services:
  main-gw:
    build:
      context: primary-build
      args:
        IGNITION_VERSION: 8.1.48
    hostname: main-host
    container_name: demo-main
    ports:
      - 9020:8088
      - 1863:1883
    volumes:
      - demo-main-data:/usr/local/bin/ignition/data
     # - ./gw-init/gold_gw.gwbk:/restore.gwbk
     # - ./gw-init/gateway-uuid.txt:/usr/local/bin/ignition/data/.uuid
     # - ./gw-init/gateway-metro-keystore:/usr/local/bin/ignition/data/local/metro-keystore
    networks:
      - gw-network
      - secondary-network
    environment:
      - IGNITION_EDITION=standard
      - GATEWAY_ADMIN_PASSWORD=katlego
      - GATEWAY_MODULES_ENABLED=alarm-notification,enterprise-administration,opc-ua,perspective,reporting,sfc,sms-notification,sql-bridge,symbol-factory,tag-historian,voice-notification,web-developer
      - ACCEPT_IGNITION_EULA=Y
    labels:
      tsdproxy.enable: true
      tsdproxy.ephemeral: false
      tsdproxy.name: demo-main
    restart: unless-stopped
    command: >
      -n main-gw
      -m 1024
   #   -r /restore.gwbk
  
networks:
  gw-network:
  secondary-network:
volumes:
  demo-main-data:
  demo-backup-data:

#are you picking up these changes?

#hello world
